repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      exclude: _vendor|vendored|examples
      args: ["--profile", "black"]
-   repo: https://github.com/python/black
    rev: 23.1.0
    hooks:
    - id: black
      pass_filenames: true
      exclude: _vendor|vendored|examples
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      pass_filenames: true
      # this seems to need to be here in addition to setup.cfg
      exclude: _vendor|vendored|__init__.py|examples
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    - id: pyupgrade
      args: ["--py37-plus"]
      exclude: _vendor|vendored|examples
